improve edit_files, add completion, etc.
adjust wpg template locations

diff --git a/.dot/aliases/functions b/.dot/aliases/functions
--- a/.dot/aliases/functions
+++ b/.dot/aliases/functions
@@ -75,106 +75,116 @@ edit_wpg_template() {
 	echo "remember fmaterial"
 }
 
-edit_config() {
-	#later likely make this check for filenames in the dotfiles repo
-	
-	#make this handle multiple filenames as input.
-	
-	#merge bal and brc into this; accept folder names etc.
-	
-	declare editor="$1" config_file="$2"
-	declare -A file_dict
 
-	add_file_without_suffix() {
-		declare suffix="$1" ; shift
-		declare filepath="$@"
-		local filename nickname
-		filename="$(basename "${filepath}")"
-		nickname="${filename%${suffix}}"
-		file_dict["${nickname}"]="${filepath}"
-	}
-	
-	add_files_without_suffix() {
-		declare suffix="$1" ; shift
-		for file in $@; do
-			add_file_without_suffix "${suffix}" "${file}"
-		done
-	}
+declare -A __edit_file_dict
+declare -a __edit_file_completions
 
-	add_file() {
-		add_file_without_suffix "" "$@"
-	}
-	
-	add_files() {
-		add_files_without_suffix "" $@
-	}
-	
-	local findargs
-	findargs="-maxdepth 1 -mindepth 1 -type f"
-    
-	add_files "$(find ~/.dot/l/ ${findargs})"
-	add_files "$(find ~/.dot/l/aliases/ ${findargs})"
-	add_files "$(find ~/.dot/l/shrc/ ${findargs})"
-	add_files "$(find /usr/local/bin/ ${findargs})"
-	add_files "$(find /usr/local/sbin/ ${findargs})"
-	add_files_without_suffix ".base" "$(find ~/.config/wpg/templates/ ${findargs} -name "*.base")"
-	add_files_without_suffix "_action" "$(find ~/.local/share/nemo/actions/ ${findargs} -name "*_action")"
-    
-	add_files /etc/{bash.bash_logout,bash.bashrc,environment,fstab,motd,profile}
-	add_files_without_suffix ".conf" /etc/lightdm/{lightdm,lightdm-webkit2-greeter,slick-greeter}.conf /etc/{makepkg,mkinitcpio,pacman,sudo,vconsole}.conf
-	add_files_without_suffix "_config" /etc/ssh/{sshd,ssh}_config
-	add_files_without_suffix ".txt" /root/setup.txt
+__make_file_dict() {
+    __edit_file_dict=()
+    __edit_file_completions=()
 
-	for key in "${!file_dict[@]}"; do
-		echo "$key : ${file_dict[$key]}"
-	done
+    __add_file_with_prefix_and_without_suffix() {
+        declare prefix="$1" ; shift
+        declare suffix="$1" ; shift
+        declare filepath="$@"
+        local filename nickname
+        #filename="$(basename "${filepath}")"
+        filename="${filepath##*/}" # needed something faster than subshell etc.
+        nickname="${prefix}${filename%${suffix}}"
+        __edit_file_dict[${nickname}]="${filepath}"
+	__edit_file_completions+=("${nickname}:${filepath}")
+    }
 
-	if [[ -f "${HOME}/.config/wpg/templates/${config_file}.base" ]]; then
-		edit_wpg_template "${editor}" "${config_file}"
-	elif [[ -f "${HOME}/.dot/l/${config_file}" ]]; then
-		${editor} "${HOME}/.dot/l/${config_file}"
-	elif [[ -f "${HOME}/.dot/l/aliases/${config_file}" ]]; then
-		${editor} "${HOME}/.dot/l/aliases/${config_file}"
-	elif [[ -f "${HOME}/.dot/l/shrc/${config_file}" ]]; then
-		${editor} "${HOME}/.dot/l/shrc/${config_file}"
-	else
-		if [[ -f "/usr/local/bin/${config_file}" ]]; then
-			${editor} "/usr/local/bin/${config_file}"
-		elif [[ -f "/usr/local/sbin/${config_file}" ]]; then
-			${editor} "/usr/local/sbin/${config_file}"
-		else
-			case "${config_file}" in
-				lightdm|lightdm-webkit2-greeter|slick-greeter)
-					${editor} "/etc/lightdm/${config_file}.conf"
-					;;
-				sshd|ssh)
-					config_file="${config_file}_config"
-					;& #fall-through
-				sshd_config|ssh_config)
-					${editor} "/etc/ssh/${config_file}"
-					;;
-				sudoers)
-					sudo visudo
-					;;
-				makepkg|mkinitcpio|pacman|sudo|vconsole)
-					config_file="${config_file}.conf"
-					;& #fall-through
-				bash.bash_logout|bash.bashrc|environment|fstab|motd|profile)
-					${editor} "/etc/${config_file}"
-					;;
-				setup)
-					${editor} "/root/${config_file}.txt"
-					;;
-				*)
-					echo "config file not found; add it to the (edit_config) function." >&2
-					;;
-			esac
-		fi
-	fi
+    add_files_with_prefix_and_without_suffix() {
+        declare prefix="$1" ; shift
+        declare suffix="$1" ; shift
+        local fix_whitespace
+        fix_whitespace=("tr" "\n" " ")
+        for file in $(echo $@ | tr "\n" " "); do
+            __add_file_with_prefix_and_without_suffix "${prefix}" "${suffix}" "${file}"
+        done
+    }
+
+    add_files_without_suffix() {
+        declare suffix="$1" ; shift
+        add_files_with_prefix_and_without_suffix "" "${suffix}" $@
+    }
+
+    add_files_with_prefix() {
+        declare prefix="$1" ; shift
+        add_files_with_prefix_and_without_suffix "${prefix}" "" $@
+    }
+
+    add_files() {
+        add_files_with_prefix_and_without_suffix "" "" $@
+    }
+
+    local findargs
+    findargs=("-maxdepth" "1" "-mindepth" "1" "-type" "f")
+
+    add_files "$(find ~/.dot/l/ ${findargs[@]})"
+    add_files "$(find ~/.dot/l/aliases/ ${findargs[@]})"
+    add_files_with_prefix "aliases/" "$(find ~/.dot/l/aliases/ ${findargs[@]})"
+    add_files "$(find ~/.dot/l/shrc/ ${findargs[@]})"
+    add_files "$(find /usr/local/bin/ ${findargs[@]})"
+    add_files_with_prefix "bin/" "$(find /usr/local/bin/ ${findargs[@]})"
+    add_files "$(find /usr/local/sbin/ ${findargs[@]})"
+    add_files_with_prefix "sbin/" "$(find /usr/local/sbin/ ${findargs[@]})"
+    add_files_without_suffix ".base" "$(find ~/.config/wpg/templates/ ${findargs[@]} -name "*.base")"
+    add_files_with_prefix_and_without_suffix "nemo-" ".nemo_action" "$(find ~/.local/share/nemo/actions/ ${findargs[@]})"
+    add_files_with_prefix "feh/" "$(find ~/.config/feh/ ${findargs[@]})"
+    add_files_with_prefix_and_without_suffix "mpv/" ".conf" "$(find ~/.config/mpv/ ${findargs[@]})"
+    add_files_with_prefix_and_without_suffix "neofetch/" ".conf" "$(find ~/.config/neofetch/ ${findargs[@]})"
+    add_files_with_prefix_and_without_suffix "nvim/" ".vim" "$(find ~/.config/nvim/ ${findargs[@]})"
+    add_files_with_prefix "polybar/bin/" "$(find ~/.config/polybar/bin/ ${findargs[@]})"
+    add_files_with_prefix_and_without_suffix "systemd/user/" ".service" "$(find ~/.config/systemd/user/ ${findargs[@]})"
+    add_files_with_prefix "wal/" "$(find ~/.config/wal/colorschemes/both/ ${findargs[@]})"
+
+    add_files /etc/{bash.bash_logout,bash.bashrc,environment,fstab,motd,profile}
+    add_files_without_suffix ".conf" /etc/lightdm/{lightdm,lightdm-webkit2-greeter,slick-greeter}.conf /etc/{makepkg,mkinitcpio,pacman,sudo,vconsole}.conf ~/.config/{mpv/mpv,kitty/kitty,wpg/wpg,redshift}.conf
+    add_files_without_suffix "_config" /etc/ssh/{sshd,ssh}_config
+    add_files_without_suffix ".txt" /root/setup.txt
+    add_files_without_suffix ".json" ~/.config/indicator-sound-switcher.json
+    add_files_without_suffix ".list" ~/.config/mimeapps.list
+
+    __edit_file_dict["yay"]="${HOME}/.config/yay/config.json"
+
+    local key print_dict
+    if [[ "${print_dict}" ]]; then
+        for key in "${!__edit_file_dict[@]}"; do
+                echo "${key} : ${__edit_file_dict[${key}]}"
+        done
+    fi
 }
 
-alias vimc='edit_config svim'
-alias atomc='edit_config satom'
+edit_file() {
+    #make this warn if the file is not tracked by dotfiles or systemfiles?
+	
+    #merge bal and brc into this; accept folder names etc.
+	
+    declare editor="$1" ; shift
+    declare filepaths=()
+
+    if ! [[ -v __edit_file_dict[@] ]]; then
+        __make_file_dict
+    fi
+    
+    local file filepath
+    for file in $@; do
+        if [[ "${__edit_file_dict[${file}]+exists}" ]]; then
+            filepaths+=("${__edit_file_dict[${file}]}")
+        else
+            echo "${file} not found; add it to the (__make_file_dict) function. (vc general)" >&2
+        fi
+    done
+    
+    if [[ ${#filepaths[@]} -ne 0 ]]; then
+        ${editor} ${filepaths[@]}
+    fi
+}
+
+alias vimc='edit_file svim'
+alias atomc='edit_file satom'
 
 alias vc='vimc'
 alias ac='atomc'
